# canario-pipeline-templates/canario-web-pipeline.yml
stages:
  - build
  - test
  - deploy

image: docker:latest

before_script:
  # Felles docker login for alle jobber
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

# Felles variabler (kan overstyres i kunderepo)
variables:
  IMAGE_REPOSITORY: "$CI_REGISTRY_IMAGE"
  TEST_PORT: "8081"

  # Stage-miljø
  STAGE_STACK_FILE: "stack/web-stage.yaml"
  STAGE_REMOTE_PATH: "/home/ubuntu/stack/web-stage.yaml"
  STAGE_STACK_NAME: "canario-web-stage"
  STAGE_URL: "http://192.168.47.26:9081"

  # Prod-miljø
  PROD_STACK_FILE: "stack/web-prod.yaml"
  PROD_REMOTE_PATH: "/home/ubuntu/stack/web-prod.yaml"
  PROD_STACK_NAME: "canario-web"
  PROD_URL: "http://192.168.47.26:8081"

  # Felles deploy-host
  DEPLOY_HOST: "ubuntu@192.168.47.26"

build:
  stage: build
  script:
    - HUMAN_TAG="LOv$CI_PIPELINE_IID"
    - FULL_HUMAN="$IMAGE_REPOSITORY:$HUMAN_TAG"

    - echo "HUMAN_TAG=$HUMAN_TAG"
    - echo "FULL_HUMAN=$FULL_HUMAN"

    - docker build -t "$FULL_HUMAN" -t "$IMAGE_REPOSITORY:latest" .
    - docker push "$FULL_HUMAN"
    - docker push "$IMAGE_REPOSITORY:latest"

test:
  stage: test
  needs: [build]
  script:
    - HUMAN_TAG="LOv$CI_PIPELINE_IID"
    - FULL_HUMAN="$IMAGE_REPOSITORY:$HUMAN_TAG"

    - echo "Tester image $FULL_HUMAN på port $TEST_PORT"
    - docker pull "$FULL_HUMAN"

    - docker rm -f "test-$CI_JOB_ID" || true
    - docker run -d -p "$TEST_PORT:80" --name "test-$CI_JOB_ID" "$FULL_HUMAN"
    - sleep 5

    - curl -f "http://localhost:$TEST_PORT/" || (echo "App svarte ikke"; docker logs "test-$CI_JOB_ID"; exit 1)

    - docker rm -f "test-$CI_JOB_ID" || true

deploy_stage:
  stage: deploy
  needs: [test]
  environment:
    name: staging
    url: "$STAGE_URL"
  script:
    - HUMAN_TAG="LOv$CI_PIPELINE_IID"
    - sed -i "s|<IMAGE_TAG>|$HUMAN_TAG|g" "$STAGE_STACK_FILE"
    - scp -o StrictHostKeyChecking=no "$STAGE_STACK_FILE" "$DEPLOY_HOST:$STAGE_REMOTE_PATH"
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_HOST" "sudo docker stack deploy -c $STAGE_REMOTE_PATH $STAGE_STACK_NAME"


deploy_prod:
  needs: [deploy_stage]
  environment:
    name: production
    url: "$PROD_URL"
  script:
    - HUMAN_TAG="LOv$CI_PIPELINE_IID"
    - echo "Bruker image-tag for prod:$HUMAN_TAG"
    - sed -i "s|<IMAGE_TAG>|$HUMAN_TAG|g" "$PROD_STACK_FILE"
    - scp -o StrictHostKeyChecking=no "$PROD_STACK_FILE" "$DEPLOY_HOST:$PROD_REMOTE_PATH"
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_HOST" "sudo docker stack deploy -c $PROD_REMOTE_PATH $PROD_STACK_NAME"

  rules:
    - if:'$CI_COMMIT_BRANCH == "main"'
