stages:
  - docker_test

image: docker:24.0.5

services:
  - name: docker:24.0.5-dind
    command: ["--tls=false"]

variables:
  DOCKER_TLS_CERTDIR: ""

docker_smoke_test:
  stage: docker_test
  script:
    - echo "=== docker version ==="
    - docker version
    - echo "=== docker info ==="
    - docker info
    - echo "=== test kjøring av container ==="
    - docker run --rm hello-world
