stages:
  - build
  - test
  - deploy_staging
  - deploy_production

# Ingen image / services her, shell-runner kjører direkte på host

variables:
  # Container registry for dette prosjektet
  IMAGE_REPOSITORY: "$CI_REGISTRY_IMAGE"

  # Testport inne i CI (lokal host)
  TEST_PORT: "8080"

  # Remote host / bruker for deploy (prod-manager)
  DEPLOY_HOST: "192.168.47.26"
  DEPLOY_USER: "ubuntu"

  # Staging-stack
  STAGE_STACK_FILE: "stack/stage.yaml"
  STAGE_REMOTE_PATH: "/home/ubuntu/stack/stage.yaml"
  STAGE_STACK_NAME: "canario-stage"
  STAGE_URL: "http://192.168.47.26:9080"

  # Production-stack
  PROD_STACK_FILE: "stack/prod.yaml"
  PROD_REMOTE_PATH: "/home/ubuntu/stack/prod.yaml"
  PROD_STACK_NAME: "canario"
  PROD_URL: "http://192.168.47.26:8080"

before_script:
  # Forutsetter at curl, ssh og docker allerede er installert på runner-host
  - echo "Runner host: $(hostname)"
  - docker version
  # Login mot GitLab Registry
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin


build_image:
  stage: build
  script:
    # Generer release-tag for dette bygget
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - IMAGE_WITH_TAG="$IMAGE_REPOSITORY:$RELEASE_TAG"

    - echo "RELEASE_TAG=$RELEASE_TAG"
    - echo "IMAGE_WITH_TAG=$IMAGE_WITH_TAG"

    # Bygg og push
    - docker build -t "$IMAGE_WITH_TAG" -t "$IMAGE_REPOSITORY:latest" .
    - docker push "$IMAGE_WITH_TAG"
    - docker push "$IMAGE_REPOSITORY:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


test_container:
  stage: test
  needs: ["build_image"]
  script:
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - IMAGE_WITH_TAG="$IMAGE_REPOSITORY:$RELEASE_TAG"

    - echo "Tester image: $IMAGE_WITH_TAG"
    - docker pull "$IMAGE_WITH_TAG"

    # Start container for enkel helsesjekk
    - docker rm -f "test-$CI_JOB_ID" || true
    - docker run -d -p "$TEST_PORT:80" --name "test-$CI_JOB_ID" "$IMAGE_WITH_TAG"

    # Vent litt og test HTTP 200 på /
    - sleep 5
    - curl -f "http://localhost:$TEST_PORT/" || (echo "App did not respond"; docker logs "test-$CI_JOB_ID"; exit 1)

    # Rydd opp
    - docker rm -f "test-$CI_JOB_ID" || true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


deploy_staging:
  stage: deploy_staging
  needs: ["test_container"]
  script:
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - echo "Using tag for staging: $RELEASE_TAG"

    # Kopi av stack-fil slik at vi ikke overskriver originalen i repoet
    - cp "$STAGE_STACK_FILE" stage_deploy.yaml
    - sed -i "s|<IMAGE_TAG>|$RELEASE_TAG|g" stage_deploy.yaml

    # SSH-nøkkel for deploy (forutsetter variabel SSH_PRIVATE_KEY i GitLab)
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

    # Kopier stack-fil og deploy stack
    - scp stage_deploy.yaml "$DEPLOY_USER@$DEPLOY_HOST:$STAGE_REMOTE_PATH"
    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "sudo docker stack deploy -c $STAGE_REMOTE_PATH $STAGE_STACK_NAME"
  environment:
    name: staging
    url: $STAGE_URL
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


deploy_production:
  stage: deploy_production
  needs: ["deploy_staging"]
  script:
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - echo "Using tag for production: $RELEASE_TAG"

    # Kopi av prod stack-fil
    - cp "$PROD_STACK_FILE" prod_deploy.yaml
    - sed -i "s|<IMAGE_TAG>|$RELEASE_TAG|g" prod_deploy.yaml

    # SSH-nøkkel for deploy (forutsetter variabel SSH_PRIVATE_KEY i GitLab)
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

    # Kopier stack-fil og deploy stack
    - scp prod_deploy.yaml "$DEPLOY_USER@$DEPLOY_HOST:$PROD_REMOTE_PATH"
    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "sudo docker stack deploy -c $PROD_REMOTE_PATH $PROD_STACK_NAME"
  environment:
    name: production
    url: $PROD_URL
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
