stages:
  - build
  - test
  - deploy_staging
  - deploy_production

image: docker:latest

# Felles variabler – de fleste kan overstyres i kunderepoet
variables:
  # Default: container registry for dette prosjektet (kunden sitt repo)
  IMAGE_REPOSITORY: $CI_REGISTRY_IMAGE

  # Testport inne i CI
  TEST_PORT: ${TEST_PORT:-8080}

  # Remote host / bruker for deploy (prod-manager)
  DEPLOY_HOST: ${DEPLOY_HOST:-192.168.47.26}
  DEPLOY_USER: ${DEPLOY_USER:-ubuntu}

  # Staging-stack (overstyres per kunde)
  STAGE_STACK_FILE: ${STAGE_STACK_FILE:-"stack/stage.yaml"}
  STAGE_REMOTE_PATH: ${STAGE_REMOTE_PATH:-"/home/ubuntu/stack/stage.yaml"}
  STAGE_STACK_NAME: ${STAGE_STACK_NAME:-"canario-stage"}
  STAGE_URL: ${STAGE_URL:-"http://192.168.47.26:9080"}

  # Production-stack (overstyres per kunde)
  PROD_STACK_FILE: ${PROD_STACK_FILE:-"stack/prod.yaml"}
  PROD_REMOTE_PATH: ${PROD_REMOTE_PATH:-"/home/ubuntu/stack/prod.yaml"}
  PROD_STACK_NAME: ${PROD_STACK_NAME:-"canario"}
  PROD_URL: ${PROD_URL:-"http://192.168.47.26:8080"}


build_image:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

    # Generer release-tag for dette bygget
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - IMAGE_WITH_TAG="$IMAGE_REPOSITORY:$RELEASE_TAG"

    - echo "RELEASE_TAG=$RELEASE_TAG"
    - echo "IMAGE_WITH_TAG=$IMAGE_WITH_TAG"

    # Bygg og push
    - docker build -t "$IMAGE_WITH_TAG" -t "$IMAGE_REPOSITORY:latest" .
    - docker push "$IMAGE_WITH_TAG"
    - docker push "$IMAGE_REPOSITORY:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


test_container:
  stage: test
  needs: ["build_image"]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - IMAGE_WITH_TAG="$IMAGE_REPOSITORY:$RELEASE_TAG"

    - docker pull "$IMAGE_WITH_TAG"
    - docker rm -f test-$CI_JOB_ID || true
    - docker run -d -p "$TEST_PORT:80" --name test-$CI_JOB_ID "$IMAGE_WITH_TAG"
    - sleep 5
    - curl -f "http://localhost:$TEST_PORT/" || (echo "App did not respond"; docker logs test-$CI_JOB_ID; exit 1)
    - docker rm -f test-$CI_JOB_ID || true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


deploy_staging:
  stage: deploy_staging
  needs: ["test_container"]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - echo "Using tag for staging: $RELEASE_TAG"
    - sed -i "s|<IMAGE_TAG>|$RELEASE_TAG|g" "$STAGE_STACK_FILE"
    - scp "$STAGE_STACK_FILE" "$DEPLOY_USER@$DEPLOY_HOST:$STAGE_REMOTE_PATH"
    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "sudo docker stack deploy -c $STAGE_REMOTE_PATH $STAGE_STACK_NAME"
  environment:
    name: staging
    url: $STAGE_URL
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy_production:
  stage: deploy_production
  needs: ["deploy_staging"]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - echo "Using tag for production: $RELEASE_TAG"
    - sed -i "s|<IMAGE_TAG>|$RELEASE_TAG|g" "$PROD_STACK_FILE"
    - scp "$PROD_STACK_FILE" "$DEPLOY_USER@$DEPLOY_HOST:$PROD_REMOTE_PATH"
    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "sudo docker stack deploy -c $PROD_REMOTE_PATH $PROD_STACK_NAME"
  environment:
    name: production
    url: $PROD_URL
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
